# -*- coding: utf-8 -*-
"""data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yq_pH4KlQgpRZux6cg5JmYRN18ylHPc2

Install MedMNIST and Fetch Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install medmnist
import medmnist
from medmnist import INFO
from torchvision import transforms
import numpy as np
import pandas as pd
import os
import math

"""Setting Up Datasets"""

def create_set(data_flag, split, download):
  """
  Downloads a MedMNIST dataset split, extracts image labels,
  and saves them to a CSV file for later use.

  Args:
      data_flag (str): Dataset name
      split     (str): Portion of Data to be used (train, val, test)
      download  (bool): Whether to download the dataset if already present (True or False)
  """

  # Convert to tensor, normalise pixels, resize to 224 x 224
  data_transform = transforms.Compose([
    transforms.Resize(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[.5], std=[.5])
  ])

  # Create labels Directory
  os.makedirs('labels', exist_ok=True)

  # Retrieve dataset metadata
  info = INFO[data_flag]
  # Get specified MNIST Class
  DataClass = getattr(medmnist, info['python_class'])
  # Dictionary saving Labels
  label_map = info['label']

  # Load the specified dataset split
  dataset = DataClass(
            split=split,
            transform=data_transform,
            download=download
        )

  # # Iterate over every image label in the dataset
  records = []
  for img_idx, label_row in enumerate(dataset.labels): # dataset.labels is a numpy array of shape (N, 1) containing integer class indices

      # Extract the integer class index from the numpy row
      label_idx  = int(label_row[0])

      # Map the integer index to class name
      label_name = label_map[str(label_idx)]

      # Store the image position, class index, and class name as one record
      records.append({
              'image_index': img_idx,
              'label_index': label_idx,
              'label_name' : label_name,
            })

  # Convert the list of records into a pandas DataFrame
  df = pd.DataFrame(records)

  # Save DF as a CSV
  csv_path = f'labels/{data_flag}_{split}_labels.csv'
  df.to_csv(csv_path, index=False)
  print(f'Saved to {csv_path}\n')

def fetch_set(data_flag, split):
  """
  Loads a previously saved label CSV back into a pandas DataFrame.

  Args:
      data_flag (str): Dataset name
      split     (str): Portion of Data to be used (train, val, test)

  Returns:
      pd.DataFrame: DataFrame with columns [image_index, label_index, label_name]
  """
  df = pd.read_csv(f'labels/{data_flag}_{split}_labels.csv')
  return df

"""PathMNIST Data Summary:"""

create_set("pathmnist", "train", True)
df1 = fetch_set("pathmnist", "train")
print("PathMNIST Train")
print(df1.label_name.value_counts())
print()
print("PathMNIST Train Percentages")
print(f"{(df1.label_name.value_counts()/df1.shape[0]) * 100}")
print()

create_set("pathmnist", "test", True)
df2 = fetch_set("pathmnist", "test")
print("PathMNIST Test")
print(df2.label_name.value_counts())
print()
print("PathMNIST Test Percentages")
print(f"{(df2.label_name.value_counts()/df2.shape[0]) * 100}")
print()


create_set("pathmnist", "val", True)
df3 = fetch_set("pathmnist", "val")
print("PathMNIST Validation")
print(df3.label_name.value_counts())
print()
print("PathMNIST Validation Percentages")
print(f"{(df3.label_name.value_counts()/df3.shape[0]) * 100}")


"""PathMNIST PreProcessing"""

path_dict = {}
percentage_of_set = {}
map = {}
for label in df1.label_name.unique():
  path_dict[label] = df1[df1.label_name == label].shape[0]
  path_dict[label] += df2[df2.label_name == label].shape[0]
  path_dict[label] += df3[df3.label_name == label].shape[0]

dataset_size = df1.shape[0] + df2.shape[0] + df3.shape[0]
train_percentage = (df1.shape[0] / dataset_size)
test_percentage = (df2.shape[0] / dataset_size)
val_percentage = (df3.shape[0] / dataset_size)
calibration_size = 9812
calibration_percentage = (calibration_size / dataset_size)
train_new_size = int((dataset_size - calibration_size) * train_percentage)
test_new_size = int((dataset_size - calibration_size) * test_percentage)
val_new_size = int((dataset_size - calibration_size) * val_percentage)

print(f"Original Size: {dataset_size}")
print(f"Train New Size: {train_new_size}, Test New Size {test_new_size}, Val New Size {val_new_size}")
print(sum((train_new_size,test_new_size,val_new_size,calibration_size)))


for label in path_dict:
  print(f"{label} Total Samples: {path_dict[label]}")
  percentage_of_set[label] = (path_dict[label] / dataset_size)
  print(f"{label} Percentage of Total Dataset: {percentage_of_set[label]}")
  f1 = df1[df1.label_name == label]
  f2 = df2[df2.label_name == label]
  f3 = df3[df3.label_name == label]
  print()
  map[label] = pd.concat([f1, f2, f3], ignore_index=True)
  print(map[label])
  print()

"""Create Equal Weight Train, Test, Validation and Calibration Datasets"""

os.makedirs('datasets', exist_ok=True)

ratios = {
    'calibration' : calibration_size,
    'train'       : train_new_size,
    'val'         : val_new_size,
    'test'        : test_new_size
}

last_subset = list(ratios.keys())[-1]
dfs = {subset: [] for subset in ratios}

for label, label_df in map.items():
    label_fraction = percentage_of_set[label]
    used_indices = set()

    for subset, subset_size in ratios.items():
      available = label_df[~label_df.image_index.isin(used_indices)]
      if subset == last_subset:
        sampled = available.copy()
      else:
        n_samples = round(subset_size * label_fraction)
        n_samples = min(n_samples, len(available))
        sampled   = available.sample(n=n_samples, random_state=42).copy()

      sampled['split'] = subset
      dfs[subset].append(sampled)
      used_indices.update(sampled.image_index)

final_sets = {}
for subset, df in dfs.items():
    final_df = pd.concat(df, ignore_index=True)
    final_df = final_df.sample(frac=1, random_state=42).reset_index(drop=True)
    final_sets[subset] = final_df
    final_df.to_csv(f'datasets/pathmnist_{subset}_labels.csv', index=False)
    print(f"Saved {subset} set to datasets/pathmnist_{subset}_labels.csv")
    print(f"{subset} size: {len(final_df)}")

df1 = pd.read_csv(f'datasets/pathmnist_train_labels.csv')
print(f"{(df1.label_name.value_counts()/df1.shape[0]) * 100}")
print()
df2 = pd.read_csv(f'datasets/pathmnist_test_labels.csv')
print(f"{(df2.label_name.value_counts()/df2.shape[0]) * 100}")
print()
df3 = pd.read_csv(f'datasets/pathmnist_calibration_labels.csv')
print(f"{(df3.label_name.value_counts()/df3.shape[0]) * 100}")
print()
df4 = pd.read_csv(f'datasets/pathmnist_val_labels.csv')
print(f"{(df4.label_name.value_counts()/df4.shape[0]) * 100}")
print()

total = df1.shape[0] + df2.shape[0] + df3.shape[0] + df4.shape[0]
print(f"Total: {total},  Train Percentage: {(df1.shape[0] / total) * 100}, Test Percentage: {(df2.shape[0] / total) * 100}, Validation Percentage: {(df3.shape[0] / total) * 100}, Calibration Percentage: {(df4.shape[0] / total) * 100}")

"""Create Test, Train, Validation for Calibration Set"""

calibration_ratios = {
    'train'       : train_percentage,
    'val'         : val_percentage,
    'test'        : test_percentage
}

last_cal_subset = list(calibration_ratios.keys())[-1]
calibration_df  = final_sets['calibration']

calibration_map = {
    label: calibration_df[calibration_df.label_name == label]
    for label in calibration_df.label_name.unique()
}

cal_dfs = {subset: [] for subset in calibration_ratios}

for label, label_df in calibration_map.items():
    label_fraction = percentage_of_set[label]
    used_indices = set()

    for subset, subset_size in calibration_ratios.items():
        available = label_df[~label_df.image_index.isin(used_indices)]

        if subset == last_cal_subset:
            sampled = available.copy()
        else:
            n_samples = round(subset_size * label_fraction * calibration_size)
            n_samples = min(n_samples, len(available))
            sampled   = available.sample(n=n_samples, random_state=42).copy()

        sampled['split'] = subset
        cal_dfs[subset].append(sampled)
        used_indices.update(sampled.image_index)

cal_final_sets = {}
for subset, df in cal_dfs.items():
    final_df = pd.concat(df, ignore_index=True)
    final_df = final_df.sample(frac=1, random_state=42).reset_index(drop=True)
    cal_final_sets[subset] = final_df
    final_df.to_csv(f'datasets/pathmnist_{subset}_calibration_labels.csv', index=False)
    print(f"Saved {subset} calibration set to datasets/pathmnist_{subset}_calibration_labels.csv")
    print(f"{subset} calibration size: {len(final_df)}")


df1 = pd.read_csv(f'datasets/pathmnist_train_calibration_labels.csv')
print(f"{(df1.label_name.value_counts()/df1.shape[0]) * 100}")
print()
df2 = pd.read_csv(f'datasets/pathmnist_test_calibration_labels.csv')
print(f"{(df2.label_name.value_counts()/df2.shape[0]) * 100}")
print()
df4 = pd.read_csv(f'datasets/pathmnist_calibration_labels.csv')
print()
df3 = pd.read_csv(f'datasets/pathmnist_val_calibration_labels.csv')
print(f"{(df4.label_name.value_counts()/df4.shape[0]) * 100}")
print()

total = df4.shape[0]
print(f"Total: {total},  Train Percentage: {(df1.shape[0] / total) * 100}, Test Percentage: {(df2.shape[0] / total) * 100}, Validation Percentage: {(df3.shape[0] / total) * 100}")

"""OCTMNIST Data Summary:"""

create_set("octmnist", "train", True)
df1 = fetch_set("octmnist", "train")
print("OctMNIST Train")
print(df1.label_name.value_counts())
print()
print("OctMNIST Train Percentages")
print(f"{(df1.label_name.value_counts()/df1.shape[0]) * 100}")
print()

create_set("octmnist", "test", True)
df2 = fetch_set("octmnist", "test")
print("OctMNIST Test")
print(df2.label_name.value_counts())
print()
print("OctMNIST Test Percentages")
print(f"{(df2.label_name.value_counts()/df2.shape[0]) * 100}")
print()


create_set("octmnist", "val", True)
df3 = fetch_set("octmnist", "val")
print("OctMNIST Validation")
print(df3.label_name.value_counts())
print()
print("OctMNIST Validation Percentages")
print(f"{(df3.label_name.value_counts()/df3.shape[0]) * 100}")

"""OCTMNIST PreProcessing"""

path_dict = {}
percentage_of_set = {}
map = {}
for label in df1.label_name.unique():
  path_dict[label] = df1[df1.label_name == label].shape[0]
  path_dict[label] += df2[df2.label_name == label].shape[0]
  path_dict[label] += df3[df3.label_name == label].shape[0]

dataset_size = df1.shape[0] + df2.shape[0] + df3.shape[0]
train_percentage = (df1.shape[0] / dataset_size)
test_percentage = (df2.shape[0] / dataset_size)
val_percentage = (df3.shape[0] / dataset_size)
calibration_size = 9812
calibration_percentage = (calibration_size / dataset_size)
train_new_size = int((dataset_size - calibration_size) * train_percentage)
test_new_size = int((dataset_size - calibration_size) * test_percentage)
val_new_size = int((dataset_size - calibration_size) * val_percentage)

print(f"Original Size: {dataset_size}")
print(f"Train New Size: {train_new_size}, Test New Size {test_new_size}, Val New Size {val_new_size}")
print(sum((train_new_size,test_new_size,val_new_size,calibration_size)))


for label in path_dict:
  print(f"{label} Total Samples: {path_dict[label]}")
  percentage_of_set[label] = (path_dict[label] / dataset_size)
  print(f"{label} Percentage of Total Dataset: {percentage_of_set[label]}")
  f1 = df1[df1.label_name == label]
  f2 = df2[df2.label_name == label]
  f3 = df3[df3.label_name == label]
  print()
  map[label] = pd.concat([f1, f2, f3], ignore_index=True)
  print(map[label])
  print()

"""Create Equal Weight Train, Test, Validation and Calibration Datasets"""

ratios = {
    'calibration' : calibration_size,
    'test'        : test_new_size,
    'train'       : train_new_size,
    'val'         : val_new_size
}

last_subset = list(ratios.keys())[-1]
dfs = {subset: [] for subset in ratios}

for label, label_df in map.items():
    label_fraction = percentage_of_set[label]
    used_indices = set()

    for subset, subset_size in ratios.items():
      available = label_df[~label_df.image_index.isin(used_indices)]
      if subset == last_subset:
        sampled = available.copy()
      else:
        n_samples = round(subset_size * label_fraction)
        n_samples = min(n_samples, len(available))
        sampled   = available.sample(n=n_samples, random_state=42).copy()

      sampled['split'] = subset
      dfs[subset].append(sampled)
      used_indices.update(sampled.image_index)

final_sets = {}
for subset, df in dfs.items():
    final_df = pd.concat(df, ignore_index=True)
    final_df = final_df.sample(frac=1, random_state=42).reset_index(drop=True)
    final_sets[subset] = final_df
    final_df.to_csv(f'datasets/octmnist_{subset}_labels.csv', index=False)
    print(f"Saved {subset} set to datasets/octnist_{subset}_labels.csv")
    print(f"{subset} size: {len(final_df)}")

print()
df1 = pd.read_csv(f'datasets/octmnist_train_labels.csv')
print(f"{(df1.label_name.value_counts()/df1.shape[0]) * 100}")
print()
df2 = pd.read_csv(f'datasets/octmnist_test_labels.csv')
print(f"{(df2.label_name.value_counts()/df2.shape[0]) * 100}")
print()
df3 = pd.read_csv(f'datasets/octmnist_calibration_labels.csv')
print(f"{(df3.label_name.value_counts()/df3.shape[0]) * 100}")
print()
df4 = pd.read_csv(f'datasets/octmnist_val_labels.csv')
print(f"{(df4.label_name.value_counts()/df4.shape[0]) * 100}")
print()

total = df1.shape[0] + df2.shape[0] + df3.shape[0] + df4.shape[0]
print(f"Total: {total},  Train Percentage: {(df1.shape[0] / total) * 100}, Test Percentage: {(df2.shape[0] / total) * 100}, Validation Percentage: {(df3.shape[0] / total) * 100}, Calibration Percentage: {(df4.shape[0] / total) * 100}")

"""Create Test, Train, Validation for Calibration Set"""

calibration_ratios = {
    'train'       : train_percentage,
    'val'         : val_percentage,
    'test'        : test_percentage
}

last_cal_subset = list(calibration_ratios.keys())[-1]
calibration_df  = final_sets['calibration']

calibration_map = {
    label: calibration_df[calibration_df.label_name == label]
    for label in calibration_df.label_name.unique()
}

cal_dfs = {subset: [] for subset in calibration_ratios}

for label, label_df in calibration_map.items():
    label_fraction = percentage_of_set[label]
    used_indices = set()

    for subset, subset_size in calibration_ratios.items():
        available = label_df[~label_df.image_index.isin(used_indices)]

        if subset == last_cal_subset:
            sampled = available.copy()
        else:
            n_samples = round(subset_size * label_fraction * calibration_size)
            n_samples = min(n_samples, len(available))
            sampled   = available.sample(n=n_samples, random_state=42).copy()

        sampled['split'] = subset
        cal_dfs[subset].append(sampled)
        used_indices.update(sampled.image_index)

cal_final_sets = {}
for subset, df in cal_dfs.items():
    final_df = pd.concat(df, ignore_index=True)
    final_df = final_df.sample(frac=1, random_state=42).reset_index(drop=True)
    cal_final_sets[subset] = final_df
    final_df.to_csv(f'datasets/octmnist_{subset}_calibration_labels.csv', index=False)
    print(f"Saved {subset} calibration set to datasets/octmnist_{subset}_calibration_labels.csv")
    print(f"{subset} calibration size: {len(final_df)}")


df1 = pd.read_csv(f'datasets/octmnist_train_calibration_labels.csv')
print(f"{(df1.label_name.value_counts()/df1.shape[0]) * 100}")
print()
df2 = pd.read_csv(f'datasets/octmnist_test_calibration_labels.csv')
print(f"{(df2.label_name.value_counts()/df2.shape[0]) * 100}")
print()
df4 = pd.read_csv(f'datasets/octmnist_calibration_labels.csv')
print()
df3 = pd.read_csv(f'datasets/octmnist_val_calibration_labels.csv')
print(f"{(df4.label_name.value_counts()/df4.shape[0]) * 100}")
print()

total = df4.shape[0]
print(f"Total: {total},  Train Percentage: {(df1.shape[0] / total) * 100}, Test Percentage: {(df2.shape[0] / total) * 100}, Validation Percentage: {(df3.shape[0] / total) * 100}")

"""TissueMNIST Data Summary:"""

create_set("tissuemnist", "train", True)
df1 = fetch_set("tissuemnist", "train")
print("TissueMNIST Train")
print(df1.label_name.value_counts())
print()
print("TissueMNIST Train Percentages")
print(f"{(df1.label_name.value_counts()/df1.shape[0]) * 100}")
print()

create_set("tissuemnist", "test", True)
df2 = fetch_set("tissuemnist", "test")
print("TissueMNIST Test")
print(df2.label_name.value_counts())
print()
print("TissueMNIST Test Percentages")
print(f"{(df2.label_name.value_counts()/df2.shape[0]) * 100}")
print()


create_set("tissuemnist", "val", True)
df3 = fetch_set("tissuemnist", "val")
print("TissueMNIST Validation")
print(df3.label_name.value_counts())
print()
print("TissueMNIST Validation Percentages")
print(f"{(df3.label_name.value_counts()/df3.shape[0]) * 100}")

"""TissueMNIST PreProcessing"""

path_dict = {}
percentage_of_set = {}
map = {}
for label in df1.label_name.unique():
  path_dict[label] = df1[df1.label_name == label].shape[0]
  path_dict[label] += df2[df2.label_name == label].shape[0]
  path_dict[label] += df3[df3.label_name == label].shape[0]

dataset_size = df1.shape[0] + df2.shape[0] + df3.shape[0]
train_percentage = (df1.shape[0] / dataset_size)
test_percentage = (df2.shape[0] / dataset_size)
val_percentage = (df3.shape[0] / dataset_size)
calibration_size = 9812
calibration_percentage = (calibration_size / dataset_size)
train_new_size = int((dataset_size - calibration_size) * train_percentage)
test_new_size = int((dataset_size - calibration_size) * test_percentage)
val_new_size = int((dataset_size - calibration_size) * val_percentage)

print(f"Original Size: {dataset_size}")
print(f"Train New Size: {train_new_size}, Test New Size {test_new_size}, Val New Size {val_new_size}")
print(sum((train_new_size,test_new_size,val_new_size,calibration_size)))


for label in path_dict:
  print(f"{label} Total Samples: {path_dict[label]}")
  percentage_of_set[label] = (path_dict[label] / dataset_size)
  print(f"{label} Percentage of Total Dataset: {percentage_of_set[label]}")
  f1 = df1[df1.label_name == label]
  f2 = df2[df2.label_name == label]
  f3 = df3[df3.label_name == label]
  print()
  map[label] = pd.concat([f1, f2, f3], ignore_index=True)
  print(map[label])
  print()

"""Create Equal Weight Train, Test, Validation and Calibration Datasets"""

ratios = {
    'calibration' : calibration_size,
    'train'       : train_new_size,
    'val'         : val_new_size,
    'test'        : test_new_size
}

last_subset = list(ratios.keys())[-1]
dfs = {subset: [] for subset in ratios}

for label, label_df in map.items():
    label_fraction = percentage_of_set[label]
    used_indices = set()

    for subset, subset_size in ratios.items():
      available = label_df[~label_df.image_index.isin(used_indices)]
      if subset == last_subset:
        sampled = available.copy()
      else:
        n_samples = round(subset_size * label_fraction)
        n_samples = min(n_samples, len(available))
        sampled   = available.sample(n=n_samples, random_state=42).copy()

      sampled['split'] = subset
      dfs[subset].append(sampled)
      used_indices.update(sampled.image_index)

final_sets = {}
for subset, df in dfs.items():
    final_df = pd.concat(df, ignore_index=True)
    final_df = final_df.sample(frac=1, random_state=42).reset_index(drop=True)
    final_sets[subset] = final_df
    final_df.to_csv(f'datasets/tissuemnist_{subset}_labels.csv', index=False)
    print(f"Saved {subset} set to datasets/tissuemmnist_{subset}_labels.csv")
    print(f"{subset} size: {len(final_df)}")

df1 = pd.read_csv(f'datasets/tissuemnist_train_labels.csv')
print(f"{(df1.label_name.value_counts()/df1.shape[0]) * 100}")
print()
df2 = pd.read_csv(f'datasets/tissuemnist_test_labels.csv')
print(f"{(df2.label_name.value_counts()/df2.shape[0]) * 100}")
print()
df3 = pd.read_csv(f'datasets/tissuemnist_calibration_labels.csv')
print(f"{(df3.label_name.value_counts()/df3.shape[0]) * 100}")
print()
df4 = pd.read_csv(f'datasets/tissuemnist_val_labels.csv')
print(f"{(df4.label_name.value_counts()/df4.shape[0]) * 100}")
print()

total = df1.shape[0] + df2.shape[0] + df3.shape[0] + df4.shape[0]
print(f"Total: {total},  Train Percentage: {(df1.shape[0] / total) * 100}, Test Percentage: {(df2.shape[0] / total) * 100}, Validation Percentage: {(df3.shape[0] / total) * 100}, Calibration Percentage: {(df4.shape[0] / total) * 100}")

"""Create Test, Train, Validation for Calibration Set"""

calibration_ratios = {
    'val'        : test_percentage,
    'test'         : val_percentage,
    'train'       : train_percentage,

}

last_cal_subset = list(calibration_ratios.keys())[-1]
calibration_df  = final_sets['calibration']

calibration_map = {
    label: calibration_df[calibration_df.label_name == label]
    for label in calibration_df.label_name.unique()
}

cal_dfs = {subset: [] for subset in calibration_ratios}

for label, label_df in calibration_map.items():
    label_fraction = percentage_of_set[label]
    used_indices = set()

    for subset, subset_size in calibration_ratios.items():
        available = label_df[~label_df.image_index.isin(used_indices)]

        if subset == last_cal_subset:
            sampled = available.copy()
        else:
            n_samples = round(subset_size * label_fraction * calibration_size)
            n_samples = min(n_samples, len(available))
            sampled   = available.sample(n=n_samples, random_state=42).copy()

        sampled['split'] = subset
        cal_dfs[subset].append(sampled)
        used_indices.update(sampled.image_index)

cal_final_sets = {}
for subset, df in cal_dfs.items():
    final_df = pd.concat(df, ignore_index=True)
    final_df = final_df.sample(frac=1, random_state=42).reset_index(drop=True)
    cal_final_sets[subset] = final_df
    final_df.to_csv(f'datasets/octmnist_{subset}_calibration_labels.csv', index=False)
    print(f"Saved {subset} calibration set to datasets/octmnist_{subset}_calibration_labels.csv")
    print(f"{subset} calibration size: {len(final_df)}")


df1 = pd.read_csv(f'datasets/octmnist_train_calibration_labels.csv')
print(f"{(df1.label_name.value_counts()/df1.shape[0]) * 100}")
print()
df2 = pd.read_csv(f'datasets/octmnist_test_calibration_labels.csv')
print(f"{(df2.label_name.value_counts()/df2.shape[0]) * 100}")
print()
df4 = pd.read_csv(f'datasets/octmnist_calibration_labels.csv')
print()
df3 = pd.read_csv(f'datasets/octmnist_val_calibration_labels.csv')
print(f"{(df4.label_name.value_counts()/df4.shape[0]) * 100}")
print()

total = df4.shape[0]
print(f"Total: {total},  Train Percentage: {(df1.shape[0] / total) * 100}, Test Percentage: {(df2.shape[0] / total) * 100}, Validation Percentage: {(df3.shape[0] / total) * 100}")

"""Data Planning:

- Calibration Size: 9812

- PathMNIST: 107180
  - 9 Labels
  - Train: 89996 or Approx 83.97%
  - Exact: 83.9671580519%
  - Test: 7180 or Approx 6.70%
  - Exact: 6.69901100952%
  - Validation: 10004 or Approx 9.33%
  - Exact: 9.33383093861%
  - If equal sampling for each label then 11909 samples for each label or 11.11% Approx

- OCTMNIST: 109309
  - 4 Labels
  - Train: 97477 or Approx 89.18%
  - Exact: 89.1756397003%
  - Test: 1000 or Approx 0.9148%
  - Exact: 0.91483775352%
  - Validation: 10832 or Approx 9.91%
  - Exact: 9.90952254618%
  - If Equal sampling for each label then 27327 samples for each label or 25% Approx


- TissueMNIST: 236386
  - 8 Labels
  - Train: 165466 or Approx 70.00%
  - Exact: 69.998223245%
  - Test: 47280 or Approx 20.00%
  - Exact: 20.0011845033%
  - Validation: 23640 or Approx 10.00%
  - Exact: 10.0005922517%
  - If Equal sampling for each label then 29548 samples for each label or 12.5% Approx

Fetch Image
"""

